apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    apisix.apache.org/app: ingress-apisix
  name: apisixpluginconfigs.apisix.apache.org
spec:
  group: apisix.apache.org
  names:
    kind: ApisixPluginConfig
    plural: apisixpluginconfigs
    shortNames:
      - apc
    singular: apisixpluginconfig
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .metadata.creationTimestamp
          name: Age
          priority: 0
          type: date
      deprecated: true
      name: v2beta3
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                plugins:
                  items:
                    properties:
                      config:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      enable:
                        type: boolean
                      name:
                        minLength: 1
                        type: string
                    type: object
                  required:
                    - name
                    - enable
                  type: array
              required:
                - plugins
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      message:
                        type: string
                      observedGeneration:
                        type: integer
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: false
      subresources:
        status: {}
    - additionalPrinterColumns:
        - jsonPath: .metadata.creationTimestamp
          name: Age
          priority: 0
          type: date
      name: v2
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                ingressClassName:
                  type: string
                plugins:
                  items:
                    properties:
                      config:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      enable:
                        type: boolean
                      name:
                        minLength: 1
                        type: string
                      secretRef:
                        type: string
                    type: object
                  required:
                    - name
                    - enable
                  type: array
              required:
                - plugins
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      message:
                        type: string
                      observedGeneration:
                        type: integer
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
