apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    apisix.apache.org/app: ingress-apisix
  name: apisixclusterconfigs.apisix.apache.org
spec:
  group: apisix.apache.org
  names:
    kind: ApisixClusterConfig
    plural: apisixclusterconfigs
    shortNames:
      - acc
    singular: apisixclusterconfig
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - deprecated: true
      name: v2beta3
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                admin:
                  properties:
                    adminKey:
                      type: string
                    baseURL:
                      pattern: https?://[^:]+:(\d+)
                      type: string
                  required:
                    - baseURL
                  type: object
                monitoring:
                  properties:
                    prometheus:
                      properties:
                        enable:
                          type: boolean
                      type: object
                    skywalking:
                      properties:
                        enable:
                          type: boolean
                        sampleRatio:
                          maximum: 1
                          minimum: 1.0e-05
                          type: number
                      type: object
                  type: object
              type: object
          type: object
      served: true
      storage: false
      subresources:
        status: {}
    - name: v2
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                admin:
                  properties:
                    adminKey:
                      type: string
                    baseURL:
                      pattern: https?://[^:]+:(\d+)
                      type: string
                  required:
                    - baseURL
                  type: object
                ingressClassName:
                  type: string
                monitoring:
                  properties:
                    prometheus:
                      properties:
                        enable:
                          type: boolean
                        prefer_name:
                          type: boolean
                      type: object
                    skywalking:
                      properties:
                        enable:
                          type: boolean
                        sampleRatio:
                          maximum: 1
                          minimum: 1.0e-05
                          type: number
                      type: object
                  type: object
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
