global:
  secrets:
    - name: etcd-secret
      values:
        - name: user
          value: root
        - name: password
          value: root

etcd:
  enabled: true
  replicaCount: 1
  existingSecret: "etcd-secret"
  existingSecretUserKey: "user"
  existingSecretPasswordKey: "password"

  auth:
    rbac:
      create: true
      existingSecret: "etcd-secret"
      existingSecretPasswordKey: "password"
