{{- if .Values.gatewayProxy.createDefault }}
apiVersion: apisix.apache.org/v1alpha1
kind: GatewayProxy
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-config
spec:
  provider:
    type: {{ .Values.gatewayProxy.provider.type }}
    controlPlane:
      endpoints:
      {{ $adminService := .Values.apisix.adminService -}}
      - http://{{ $adminService.name }}.{{ $adminService.namespace }}:{{ $adminService.port }}
      {{- with .Values.gatewayProxy.provider.controlPlane.auth }}
      auth:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
