apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.config.kubernetes.ingressClass | quote }}
spec:
  controller: apisix.apache.org/apisix-ingress # fix: https://github.com/apache/apisix-ingress-controller/issues/1653
