apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.config.kubernetes.ingressClass }}
  {{- if .Values.config.kubernetes.defaultIngressClass }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: {{ .Values.config.controllerName | default "apisix.apache.org/apisix-ingress-controller" }}
  {{- if .Values.gatewayProxy.createDefault }}
  parameters:
    apiGroup: apisix.apache.org
    kind: GatewayProxy
    name: {{ .Release.Name }}-config
    namespace: {{ .Release.Namespace }}
    scope: Namespace
  {{- end}}
