apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.config.kubernetes.inressClass }}
spec:
  controller: {{ .Values.config.controllerName | default "apisix.apache.org/apisix-ingress-controller" }}
