apiVersion: v1
kind: Service
metadata:
  name: {{ include "apisix-ingress-controller.fullname" . }}-apisix-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apisix-ingress-controller.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9443
  selector:
    {{- include "apisix-ingress-controller.selectorLabels" . | nindent 4 }}
  type: NodePort
