{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "apisix-ingress-controller.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
spec:
  endpoints:
  - targetPort: http
    scheme: http
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ template "apisix-ingress-controller.namespace" . }}

  selector:
    matchLabels:
      {{- include "apisix-ingress-controller.labels" . | nindent 6 }}
{{- end }}

