#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if and (.Values.apisix.enabled) (eq .Values.apisix.kind "DaemonSet") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "apisix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apisix.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "apisix.selectorLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  updateStrategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.apisix.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "apisix.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.apisix.image.repository }}:{{ .Values.apisix.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apisix.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.http.containerPort }}
              protocol: TCP
            - name: tls
              containerPort: {{ .Values.gateway.tls.containerPort }}
              protocol: TCP
            {{- if .Values.admin.enabled }}
            - name: admin
              containerPort: {{ .Values.admin.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.serviceMonitor.enabled }}
            - name: prometheus
              containerPort: {{ .Values.serviceMonitor.containerPort }}
              protocol: TCP
            {{- end }}
            {{- if and .Values.gateway.stream.enabled (or (gt (len .Values.gateway.stream.tcp) 0) (gt (len .Values.gateway.stream.udp) 0)) }}
            {{- with .Values.gateway.stream }}
            {{- if (gt (len .tcp) 0) }}
            {{- range $index, $port := .tcp }}
            - name: proxy-tcp-{{ $index | toString }}
              containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
            {{- end }}
            {{- if (gt (len .udp) 0) }}
            {{- range $index, $port := .udp }}
            - name: proxy-udp-{{ $index | toString }}
              containerPort: {{ $port }}
              protocol: UDP
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.gateway.http.containerPort }}
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - "sleep 30"
          volumeMounts:
            {{- if .Values.apisix.setIDFromPodUID }}
            - mountPath: /usr/local/apisix/conf/apisix.uid
              name: id
              subPath: apisix.uid
            {{- end }}
            - mountPath: /usr/local/apisix/conf/config.yaml
              name: apisix-config
              subPath: config.yaml
            {{- if and .Values.gateway.tls.enabled .Values.gateway.tls.existingCASecret }}
            - mountPath: /usr/local/apisix/conf/ssl/{{ .Values.gateway.tls.certCAFilename }}
              name: ssl
              subPath: {{ .Values.gateway.tls.certCAFilename }}
            {{- end }}
            {{- if .Values.etcd.auth.tls.enabled }}
            - mountPath: /etcd-ssl
              name: etcd-ssl
            {{- end }}
          {{- if .Values.customPlugins.enabled }}
          {{- range $plugin := .Values.customPlugins.plugins }}
          {{- range $mount := $plugin.configMap.mounts }}
            - mountPath: {{ $mount.path }}
              name: plugin-{{ $plugin.configMap.name }}
              subPath: {{ $mount.key }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.apisix.luaModuleHook.enabled }}
          {{- range $mount := .Values.apisix.luaModuleHook.configMapRef.mounts }}
            - mountPath: {{ $mount.path }}
              name: lua-module-hook
              subPath: {{ $mount.key }}
          {{- end }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.apisix.resources | nindent 12 }}
      {{- if .Values.etcd.enabled }}
      initContainers:
      - name: wait-etcd
        image: {{ .Values.initContainer.image }}:{{ .Values.initContainer.tag }}
        command: ['sh', '-c', "until nc -z {{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc.{{ .Values.etcd.clusterDomain }} {{ .Values.etcd.service.port }}; do echo waiting for etcd `date`; sleep 2; done;"]
      {{- end }}
      volumes:
        - configMap:
            name: {{ include "apisix.fullname" . }}
          name: apisix-config
        {{- if and .Values.gateway.tls.enabled .Values.gateway.tls.existingCASecret }}
        - secret:
            secretName: {{ .Values.gateway.tls.existingCASecret | quote }}
          name: ssl
        {{- end }}
        {{- if .Values.etcd.auth.tls.enabled }}
        - secret:
            secretName: {{ .Values.etcd.auth.tls.existingSecret | quote }}
          name: etcd-ssl
        {{- end }}
        {{- if .Values.apisix.setIDFromPodUID }}
        - downwardAPI:
            items:
              - path: "apisix.uid"
                fieldRef:
                  fieldPath: metadata.uid
          name: id
        {{- end }}
      {{- if .Values.customPlugins.enabled }}
      {{- range $plugin := .Values.customPlugins.plugins }}
        - name: plugin-{{ $plugin.configMap.name }}
          configMap:
            name: {{ $plugin.configMap.name }}
      {{- end }}
      {{- end }}
      {{- if .Values.apisix.luaModuleHook.enabled }}
        - name: lua-module-hook
          configMap:
            name: {{ .Values.apisix.luaModuleHook.configMapRef.name }}
      {{- end }}
      {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
      {{- with .Values.apisix.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- with .Values.apisix.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apisix.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
