{{- range $secret := .Values.global.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  {{- range $value := $secret.values }}
  {{ $value.name }}: {{ $value.value | b64enc | quote }}
  {{- end }}
---
{{- end }}
